version: '3'

services:
  redis:
    image: redis
    container_name: redis-local
    volumes:
      - redis:/var/lib/redis/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    env_file:
      - .env.redis
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD:-default_passw}      
    command:
      - /bin/sh
      - -c
      - redis-server --requirepass "$${REDIS_PASSWORD:?REDIS_PASSWORD missing}"

volumes:
  redis:
